name: CI/CD counter app

on:
  push:
    branches:
    - master

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
   
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: easingthemes/ssh-deploy@main
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            TARGET_DIR : ${{ secrtets.TARGET }}
